# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtnormc <- function(a, b) {
    .Call('_bnmr_rtnormc', PACKAGE = 'bnmr', a, b)
}

rtmvnormc <- function(m, V, w, n) {
    .Call('_bnmr_rtmvnormc', PACKAGE = 'bnmr', m, V, w, n)
}

updatealpha <- function(alpha, nc, alpha_a, alpha_b, M) {
    .Call('_bnmr_updatealpha', PACKAGE = 'bnmr', alpha, nc, alpha_a, alpha_b, M)
}

betatothetaandS <- function(beta) {
    .Call('_bnmr_betatothetaandS', PACKAGE = 'bnmr', beta)
}

updatebeta <- function(y, BA, beta, nc, theta, M, pi_a, pi_b, alpha, sig2inv, phi2inv, mu, j, n) {
    .Call('_bnmr_updatebeta', PACKAGE = 'bnmr', y, BA, beta, nc, theta, M, pi_a, pi_b, alpha, sig2inv, phi2inv, mu, j, n)
}

mcmc <- function(y, BA, M, pi_a, pi_b, alpha_a, alpha_b, n, mu0, phi2inv, intvarinv, thin, loops) {
    .Call('_bnmr_mcmc', PACKAGE = 'bnmr', y, BA, M, pi_a, pi_b, alpha_a, alpha_b, n, mu0, phi2inv, intvarinv, thin, loops)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_bnmr_RcppExport_registerCCallable', PACKAGE = 'bnmr')
})
